"""updated posts model

Revision ID: 2321b711e657
Revises: 4c05a05d32d8
Create Date: 2021-10-07 14:57:49.064008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2321b711e657'
down_revision = '4c05a05d32d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('caption', sa.String(length=280), nullable=False))
    op.add_column('posts', sa.Column('image', sa.String(length=280), nullable=False))
    op.drop_column('posts', 'content')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('content', sa.VARCHAR(length=280), autoincrement=False, nullable=False))
    op.drop_column('posts', 'image')
    op.drop_column('posts', 'caption')
    # ### end Alembic commands ###
