"""updated users model


Revision ID: 894328375f13
Revises: 2321b711e657
Create Date: 2021-10-07 19:45:10.565106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '894328375f13'
down_revision = '2321b711e657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    # ### end Alembic commands ###
